# Generated by Django 6.0.3 on 2026-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_description_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excert',
            field=models.CharField(max_length=200),
        ),
    ]
