# Generated by Django 6.0.3 on 2026-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
