# Generated by Django 6.0.3 on 2026-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_blogs',
            field=models.ManyToManyField(blank=True, related_name='RelatedBlogs', to='blog.blogpost'),
        ),
    ]
