# Generated by Django 6.0.3 on 2026-04-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_category_id_alter_tag_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadLaterBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavedByUsers', to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReadLaterBlogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read Later Blog',
                'verbose_name_plural': 'Read Later Blogs',
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
