# Generated by Django 4.2.11 on 2026-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_sociallinks_alter_aboutus_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialLinks',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
